package KieRule;

import drool.in.springdrools.model.Order;

rule "HDFC"
    when
        orderObject : Order(cardType=="HDFC" && price>10000)
    then
        orderObject.setDiscount(10);

    end

rule "ICICI"
    when
        orderObject : Order(cardType=="ICICI" && price>15000)
    then
        orderObject.setDiscount(8);
         System.out.println("Hello ICICI Rules");
    end

rule "DBS"
    when
        orderObject : Order(cardType=="DBS" && price>15000)
    then
        orderObject.setDiscount(15);
    end

rule "SBI"
    when
        orderObject : Order(cardType=="SBI" && price>20000)
    then
        orderObject.setDiscount(20);
end